### ISSUE TITLE
Spectrum2 in gateway mode - registration form + submit going to random transports

### ISSUE THREAD

**Issue by mbirth** [hanzz/spectrum2#178]
I've setup ejabberd 16.12.0-beta1 using their [Docker-image](https://hub.docker.com/r/ejabberd/ecs/) and Spectrum2 2.0.1 (`:latest`) from the official [Docker-image](https://hub.docker.com/r/spectrum2/spectrum2/).

And as soon as I have 2 or more transports active (e.g. Twitter, WhatsApp/TransWhat, Telegram and ICQ), I can't reliably register new accounts to them. I've tried Gajim, Pidgin and PSI and all show the same behaviour.

Service Discovery works and shows all transports but when clicking on one to "register", the dialog already shows login fields from a different one. E.g. I click "Twitter" and the dialog shows "Enter your UIN" (which I've set in the ICQ's config file.) Once in a while, I get the correct registration form, but when I submit the data, it - again - goes to some random transport for which it isn't meant for. E.g. I get the correct "Enter your Twitter handle" dialog, but when entering the info and clicking OK, nothing happens and from checking the transport's databases, I might find the entered data in the database of the e.g. Telegram transport.

What is this?

**Comment by vitalyster** [comment]
Looks like ejabberd misconfiguration

**Comment by mbirth** [comment]
@vitalyster What is there to configure despite

```
  -
    port: 8888
    module: ejabberd_service
    access: all
    shaper_rule: fast
    hosts:
      "icq.mydomain.com":
        password: "secret"
      "telegram.mydomain.com":
        password: "secret"
      "twitter.mydomain.com":
        password: "secret"
      "whatsapp.mydomain.com":
        password: "secret"
```
